kind: Service 
apiVersion: v1 
metadata:
  name: jlab-service
  namespace: jlab
spec:
  type: NodePort
  selector:
    app: jupyterlab
  ports:
    - nodePort: 30888
      port: 8888
      targetPort: 8888
